model: save_model/stage_two/with_class/aug20/average_model_56-60.pt
src: dataset/stage_two/with_class/top10_sideprod_src-test_with_class.txt
output: results/stage_two/with_class/average_model_56-60-results.txt
gpu: 0
beam_size: 10
n_best: 10
batch_size: 8192
batch_type: tokens
max_length: 500
seed: 0


